// <auto-generated />
using System;
using COVID19.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COVID19.Migrations
{
    [DbContext(typeof(Covid19DbContext))]
    partial class Covid19DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COVID19.Entities.CountryRegion", b =>
                {
                    b.Property<int>("CountryRegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryRegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryRegionId");

                    b.ToTable("CountryRegions");
                });

            modelBuilder.Entity("COVID19.Entities.CovidGlobalConfirmed", b =>
                {
                    b.Property<int>("CovidGlobalConfirmedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CovidGlobalConfirmedId"));

                    b.Property<int>("ConfirmedCases")
                        .HasColumnType("int");

                    b.Property<int?>("CountryRegionId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceStateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CovidGlobalConfirmedId");

                    b.HasIndex("CountryRegionId");

                    b.HasIndex("ProvinceStateId");

                    b.ToTable("CovidGlobalConfirmeds");
                });

            modelBuilder.Entity("COVID19.Entities.CovidGlobalDeaths", b =>
                {
                    b.Property<int>("CovidGlobalDeathsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CovidGlobalDeathsId"));

                    b.Property<int?>("CountryRegionId")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceStateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CovidGlobalDeathsId");

                    b.HasIndex("CountryRegionId");

                    b.HasIndex("ProvinceStateId");

                    b.ToTable("CovidGlobalDeaths");
                });

            modelBuilder.Entity("COVID19.Entities.CovidGlobalRecovered", b =>
                {
                    b.Property<int>("CovidGlobalRecoveredId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CovidGlobalRecoveredId"));

                    b.Property<int?>("CountryRegionId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceStateId")
                        .HasColumnType("int");

                    b.Property<int>("RecoveredCases")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CovidGlobalRecoveredId");

                    b.HasIndex("CountryRegionId");

                    b.HasIndex("ProvinceStateId");

                    b.ToTable("CovidGlobalRecovereds");
                });

            modelBuilder.Entity("COVID19.Entities.DailyReport", b =>
                {
                    b.Property<int>("DailyReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyReportId"));

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("Confirmed")
                        .HasColumnType("int");

                    b.Property<int?>("CountryRegionId")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int?>("FIPS")
                        .HasColumnType("int");

                    b.Property<double?>("HospitalizationRate")
                        .HasColumnType("float");

                    b.Property<string>("ISO3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("IncidentRate")
                        .HasColumnType("float");

                    b.Property<long?>("PeopleHospitalized")
                        .HasColumnType("bigint");

                    b.Property<long?>("PeopleTested")
                        .HasColumnType("bigint");

                    b.Property<int?>("ProvinceStateId")
                        .HasColumnType("int");

                    b.Property<int>("Recovered")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TestingRate")
                        .HasColumnType("float");

                    b.Property<int?>("UID")
                        .HasColumnType("int");

                    b.HasKey("DailyReportId");

                    b.HasIndex("CountryRegionId");

                    b.HasIndex("ProvinceStateId");

                    b.ToTable("DailyReport");
                });

            modelBuilder.Entity("COVID19.Entities.ProvinceState", b =>
                {
                    b.Property<int>("ProvinceStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceStateId"));

                    b.Property<int?>("CountryRegionId")
                        .HasColumnType("int");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceStateId");

                    b.HasIndex("CountryRegionId");

                    b.ToTable("ProvinceStates");
                });

            modelBuilder.Entity("COVID19.Entities.CovidGlobalConfirmed", b =>
                {
                    b.HasOne("COVID19.Entities.CountryRegion", "CountryRegion")
                        .WithMany()
                        .HasForeignKey("CountryRegionId");

                    b.HasOne("COVID19.Entities.ProvinceState", "ProvinceState")
                        .WithMany("CovidGlobalConfirmeds")
                        .HasForeignKey("ProvinceStateId");

                    b.Navigation("CountryRegion");

                    b.Navigation("ProvinceState");
                });

            modelBuilder.Entity("COVID19.Entities.CovidGlobalDeaths", b =>
                {
                    b.HasOne("COVID19.Entities.CountryRegion", "CountryRegion")
                        .WithMany()
                        .HasForeignKey("CountryRegionId");

                    b.HasOne("COVID19.Entities.ProvinceState", "ProvinceState")
                        .WithMany("CovidGlobalDeaths")
                        .HasForeignKey("ProvinceStateId");

                    b.Navigation("CountryRegion");

                    b.Navigation("ProvinceState");
                });

            modelBuilder.Entity("COVID19.Entities.CovidGlobalRecovered", b =>
                {
                    b.HasOne("COVID19.Entities.CountryRegion", "CountryRegion")
                        .WithMany()
                        .HasForeignKey("CountryRegionId");

                    b.HasOne("COVID19.Entities.ProvinceState", "ProvinceState")
                        .WithMany("CovidGlobalRecovereds")
                        .HasForeignKey("ProvinceStateId");

                    b.Navigation("CountryRegion");

                    b.Navigation("ProvinceState");
                });

            modelBuilder.Entity("COVID19.Entities.DailyReport", b =>
                {
                    b.HasOne("COVID19.Entities.CountryRegion", "CountryRegion")
                        .WithMany()
                        .HasForeignKey("CountryRegionId");

                    b.HasOne("COVID19.Entities.ProvinceState", "ProvinceState")
                        .WithMany("DailyReports")
                        .HasForeignKey("ProvinceStateId");

                    b.Navigation("CountryRegion");

                    b.Navigation("ProvinceState");
                });

            modelBuilder.Entity("COVID19.Entities.ProvinceState", b =>
                {
                    b.HasOne("COVID19.Entities.CountryRegion", "CountryRegion")
                        .WithMany("ProvinceStates")
                        .HasForeignKey("CountryRegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CountryRegion");
                });

            modelBuilder.Entity("COVID19.Entities.CountryRegion", b =>
                {
                    b.Navigation("ProvinceStates");
                });

            modelBuilder.Entity("COVID19.Entities.ProvinceState", b =>
                {
                    b.Navigation("CovidGlobalConfirmeds");

                    b.Navigation("CovidGlobalDeaths");

                    b.Navigation("CovidGlobalRecovereds");

                    b.Navigation("DailyReports");
                });
#pragma warning restore 612, 618
        }
    }
}
